USE LIBRARY;

DROP TABLE IF EXISTS BOOK_X_AUTHOR;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS AUTHOR_ROLE;
DROP TABLE IF EXISTS LOG;

CREATE TABLE AUTHOR_ROLE
(
    AUTHOR_ROLE_ID      INT             PRIMARY KEY IDENTITY(1,1),
    AUTHOR_ROLE_NAME    VARCHAR(250)    NOT NULL,
    AUTHOR_ROLE_DESC    VARCHAR(MAX)    NULL
);

CREATE TABLE AUTHOR
(
    AUTHOR_ID           INT             PRIMARY KEY IDENTITY(1,1),
    FIRST_NAME          VARCHAR(250)    NOT NULL,
    LAST_NAME           VARCHAR(250)    NOT NULL,
    NATIONALITY_SHORT   VARCHAR(5)      NULL,
    AUTHOR_DESC         VARCHAR(MAX)    NULL
);

CREATE TABLE BOOK
(
    BOOK_ID             INT             PRIMARY KEY IDENTITY(1,1),
    BOOK_TITLE          VARCHAR(1000)   NOT NULL,
    BOOK_PAGE_NUMBER    INT             NOT NULL,
    BOOK_ISBN           VARCHAR(13)     NOT NULL,
    BOOK_RESUME         VARCHAR(MAX)    NULL   
);

CREATE TABLE BOOK_X_AUTHOR
(
    BOOK_ID             INT                 NOT NULL        FOREIGN KEY REFERENCES BOOK(BOOK_ID),
    AUTHOR_ID           INT                 NOT NULL        FOREIGN KEY REFERENCES AUTHOR(AUTHOR_ID),
    AUTHOR_ROLE_ID      INT                 NOT NULL        FOREIGN KEY REFERENCES AUTHOR_ROLE(AUTHOR_ROLE_ID),
    CONSTRAINT          PK_BOOK_X_AUTHOR    PRIMARY KEY     (BOOK_ID, AUTHOR_ID)
);

CREATE TABLE LOG
(
    LOG_ID              INT                     PRIMARY KEY IDENTITY(-1000000,1),
    LOG_TYPE            VARCHAR(100)            NOT NULL,
    LOG_TIME            TIMESTAMP               NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOG_TEXT            VARCHAR(MAX)            NOT NULL,
    LOG_SEVERITY        VARCHAR(100)            NOT NULL
);